# Generated by Django 6.0.4 on 2026-04-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='raw_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recommended_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('homework', 'Домашнее задание'), ('project', 'Проект'), ('exam', 'Контрольная/Экзамен'), ('personal', 'Личная задача'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
